### ISSUE TITLE
Custom FormsFX control does not work

### ISSUE THREAD

**Issue by incendium** [dlsc-software-consulting-gmbh/PreferencesFX#177]
I am running into an issue trying to create a password field.  When I try to use the `Setting.of` call which takes a custom FormsFx control (PasswordField), PreferencesFx fails with a ClassCastException.

Stacktrace:

```
java.lang.ClassCastException: com.dlsc.formsfx.view.controls.SimplePasswordControl cannot be cast to com.dlsc.preferencesfx.formsfx.view.controls.SimpleControl
	at com.dlsc.preferencesfx.formsfx.view.renderer.PreferencesFxGroupRenderer.layoutParts(PreferencesFxGroupRenderer.java:90)
	at com.dlsc.preferencesfx.formsfx.view.renderer.PreferencesFxGroupRenderer.init(PreferencesFxGroupRenderer.java:53)
	at com.dlsc.preferencesfx.formsfx.view.renderer.PreferencesFxGroupRenderer.<init>(PreferencesFxGroupRenderer.java:45)
	at com.dlsc.preferencesfx.formsfx.view.renderer.PreferencesFxFormRenderer.lambda$initializeParts$0(PreferencesFxFormRenderer.java:50)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.dlsc.preferencesfx.formsfx.view.renderer.PreferencesFxFormRenderer.initializeParts(PreferencesFxFormRenderer.java:51)
	at com.dlsc.formsfx.view.util.ViewMixin.init(ViewMixin.java:45)
	at com.dlsc.preferencesfx.formsfx.view.renderer.PreferencesFxFormRenderer.<init>(PreferencesFxFormRenderer.java:36)
	at com.dlsc.preferencesfx.view.CategoryView.initializeFormRenderer(CategoryView.java:48)
	at com.dlsc.preferencesfx.view.CategoryPresenter.initializeViewParts(CategoryPresenter.java:60)
	at com.dlsc.preferencesfx.view.Presenter.init(Presenter.java:15)
	at com.dlsc.preferencesfx.view.CategoryPresenter.<init>(CategoryPresenter.java:51)
	at com.dlsc.preferencesfx.PreferencesFx.lambda$initializeCategoryViews$0(PreferencesFx.java:123)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.dlsc.preferencesfx.PreferencesFx.initializeCategoryViews(PreferencesFx.java:121)
	at com.dlsc.preferencesfx.PreferencesFx.init(PreferencesFx.java:77)
	at com.dlsc.preferencesfx.PreferencesFx.<init>(PreferencesFx.java:64)
	at com.dlsc.preferencesfx.PreferencesFx.<init>(PreferencesFx.java:55)
	at com.dlsc.preferencesfx.PreferencesFx.of(PreferencesFx.java:102)
	at org.example.MainView$root$1$1$1.invoke(Main.kt:21)
	at org.example.MainView$root$1$1$1.invoke(Main.kt:17)
	at tornadofx.ControlsKt$action$2.handle(Controls.kt:437)
	at tornadofx.ControlsKt$action$2.handle(Controls.kt)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
```

Code in question (Kotlin + TornadoFX):
```kotlin
                PreferencesFx.of(Settings::class.java,
                    Category.of("General",
                        Setting.of("Username", Settings.usernameProperty),
                        Setting.of("Password",
                            Field.ofPasswordType(Settings.passwordProperty),
                            Settings.passwordProperty
                        )
                    )
                ).show()
```

Full demo project: https://github.com/incendium/preferencesfx-custom-formfx-field

**Comment by VirtualTim** [comment]
I'm running into the same issue with the latest PreferencesFX.
@incendium, did you find a workaround?

**Comment by incendium** [comment]
No, I gave up and manually created the form I needed.

**Comment by reikjarloekl** [comment]
It is unclear, why the library does not simply reference the FormsFx lib so that all controls would be available. Instead, the FormsFx code seems to have been copied into this lib but only partly.

**Comment by VirtualTim** [comment]
> It is unclear, why the library does not simply reference the FormsFx lib so that all controls would be available. Instead, the FormsFx code seems to have been copied into this lib but only partly.

Yeah I had the same question.
