### ISSUE TITLE
Null Pointer Exception with de.jensd.fx.fontawesomefx.commons/de.jensd.fx.glyphs.GlyphsFactory.loadFont(GlyphsFactory.java:64)?

### ISSUE THREAD

**Issue by sreese4u** [dlsc-software-consulting-gmbh/PreferencesFX#296]
Any idea why am I getting this on a Mac? I use Java 13. I am calling this method.

```
public void tryThis(String name) {
    PreferencesFx preferencesFx = PreferencesFx.of(this.getClass(),
        Category.of(name,
            Setting.of("Name", new SimpleStringProperty(""))
        )
    ).instantPersistent(true).dialogTitle(name + " Properties");

    preferencesFx.show();
  }
```

And I am getting this exception.

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at de.jensd.fx.fontawesomefx.commons/de.jensd.fx.glyphs.GlyphsFactory.loadFont(GlyphsFactory.java:64)
	at de.jensd.fx.fontawesomefx.commons/de.jensd.fx.glyphs.GlyphsFactory.<init>(GlyphsFactory.java:38)
	at de.jensd.fx.fontawesomefx.fontawesome/de.jensd.fx.glyphs.fontawesome.utils.FontAwesomeIconFactory.<init>(FontAwesomeIconFactory.java:28)
	at de.jensd.fx.fontawesomefx.fontawesome/de.jensd.fx.glyphs.fontawesome.utils.FontAwesomeIconFactory.get(FontAwesomeIconFactory.java:33)
	at com.dlsc.preferencesfx@11.7.0/com.dlsc.preferencesfx.view.UndoRedoBox.<init>(UndoRedoBox.java:17)
	at com.dlsc.preferencesfx@11.7.0/com.dlsc.preferencesfx.PreferencesFx.init(PreferencesFx.java:71)
	at com.dlsc.preferencesfx@11.7.0/com.dlsc.preferencesfx.PreferencesFx.<init>(PreferencesFx.java:64)
	at com.dlsc.preferencesfx@11.7.0/com.dlsc.preferencesfx.PreferencesFx.<init>(PreferencesFx.java:55)
	at com.dlsc.preferencesfx@11.7.0/com.dlsc.preferencesfx.PreferencesFx.of(PreferencesFx.java:102)
	at my.package.tryThis(Clusters.java:38)
	at my.package.Main.main(Main.java:17)
	... 11 more
Caused by: java.lang.NullPointerException
	at de.jensd.fx.fontawesomefx.commons/de.jensd.fx.glyphs.GlyphsFactory.loadFont(GlyphsFactory.java:62)
	... 21 more
Exception running application my.package.Main
```

I tried adding "fontawesomefx-fontawesome" 4.7.0-11 and "fontawesomefx-commons" 11-0 as Maven dependency (excluded it for preferencesfx-core) but that did not help.

Looks a lot like https://bitbucket.org/Jerady/fontawesomefx/issues/70/nullpointerexception-in.

I debugged it to the https://bitbucket.org/Jerady/fontawesomefx/src/6cbf97484669c4ab79318a158e1dadf59363c85c/fontawesomefx/fontawesomefx-commons/src/main/java/de/jensd/fx/glyphs/GlyphsFactory.java#lines-62 line and it looks like resource loading does not work on Mac OS X.

**Comment by sreese4u** [comment]
In case someone wants to patch FontAwesomeFX themselves for it to work, I "documented" it at https://stackoverflow.com/questions/65374578/getresource-method-returns-null-while-loading-font-file-but-why/65376007#65376007.
You have to use the newest (11.0.3 currently) ControlsFX library as well for PreferencesFX to work.
