### ISSUE TITLE
gson dependency breaking in version 11.15.0 and above

### ISSUE THREAD

**Issue by cupendra** [dlsc-software-consulting-gmbh/PreferencesFX#451]
The below error occurs while loading the PreferencesFx module for the first time. The preferences widget doesn't get displayed. 

Caused by: java.lang.ClassNotFoundException: com.google.gson.reflect.TypeToken
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

**Comment by cupendra** [comment]
Users have to explicitly add the gson module as required to their respective application module-info
